name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build -t test_image .

      - name: Run Tests
        run: |
          docker run --rm -v ${{ github.workspace }}/reports/allure-results:/app/reports/allure-results test_image
          
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: reports/allure-results

