name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build Docker image
        run: docker build -t test_image .

      - name: Run Tests
        run: |
          docker run --rm -v ${{ github.workspace }}/reports/allure-results:/app/reports/allure-results test_image

      - name: Generate Allure Report
        uses: kryvetskyi/github-allure-report-action@v1.3.0
        with:
          report_folder: reports/allure-results
          report_output_folder: reports/allure-report


