name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t test_image:${{ github.sha }} .

      - name: Run Tests
        run: |
          docker run --rm -v /data/allure-results:/app/reports/allure-results --name test_container test_image:${{ github.sha }}

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure Report
        run: |
          allure generate /data/allure-results -o /data/allure-report --clean

      - name: Archive Allure Report
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: /data/allure-report

