name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker ps -a
          docker images
          pwd
          ls -la
          docker build -t test_image:${{ github.sha }} .

  test:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker ps -a
          docker images
          whoami
          pwd
          ls -la
          docker run --name test_container test_image:${{ github.sha }}

  cleanup:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}

    steps:
      - name: List Docker images
        run: docker images

      - name: Cleanup Docker image
        run: |
          docker ps -a
          docker images
          whoami
          pwd
          ls -la
          docker rmi test_image:${{ github.sha }}


