name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t test_image .
          docker ps -a
          docker images

  test:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker ps -a
          docker images
          docker run --name test_container test_image

