name: Run Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add workflow_dispatch for manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t test_image:${{ github.sha }} .

      - name: Run Tests
        run: |
          docker run --rm --name test_container test_image:${{ github.sha }}

  cleanup:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }}
    steps:
      - name: Cleanup Docker image
        run: |
          docker rmi test_image:${{ github.sha }}





